In [14]:
import pandas as pd
maindf = pd.read_csv('/Users/ranbarasan/Documents/NFLWinLossNormalChart.csv')

In [16]:
del maindf["Unnamed: 0"]
del maindf["Unnamed: 33"]
maindf = maindf.drop(index = 32)

In [28]:
maindf

Bills  Patriots  Jets  Dolphins  Raiders  Chargers  Chiefs  Broncos  \
0       0         2     2         2        1         1       0        1   
1       0         0     2         1        1         1       0        0   
2       0         0     0         0        0         0       0        0   
3       0         1     2         0        1         1       0        0   
4       0         0     1         0        0         1       1        2   
5       0         0     1         0        1         0       1        1   
6       1         1     1         1        1         1       0        2   
7       0         1     1         1        0         1       0        0   
8       0         0     0         0        0         0       0        0   
9       0         0     0         0        0         0       0        0   
10      0         0     0         0        0         0       0        0   
11      0         0     0         0        0         0       0        1   
12      1         0     0         0        0         0       0        1   
13      0         0     1         0        1         0       0        0   
14      0         0     0         0        0         0       0        0   
15      0         1     0         0        0         0       0        0   
16      0         1     1         0        0         0       0        0   
17      0         1     1         1        0         0       0        0   
18      1         0     1         0        0         0       0        0   
19      0         1     0         0        0         0       0        0   
20      0         0     0         0        0         0       0        0   
21      0         0     0         0        0         0       0        0   
22      0         0     0         0        0         0       0        0   
23      0         0     0         0        0         0       0        0   
24      0         0     0         0        0         0       0        0   
25      0         0     0         0        0         0       0        0   
26      0         0     0         0        0         0       0        0   
27      0         0     0         0        0         0       0        0   
28      0         0     0         0        1         1       0        1   
29      0         0     0         0        0         1       0        1   
30      0         0     0         0        1         0       0        1   
31      0         0     0         0        0         1       0        0   

    Bengals  Ravens  ...  Eagles  Giants  Packers  Vikings  Bears  Lions  \
0       0.0       0  ...     0.0       0        0        0      0      0   
1       0.0       1  ...     0.0       0        0        0      0      0   
2       0.0       0  ...     0.0       0        0        0      0      0   
3       1.0       0  ...     0.0       0        0        0      0      0   
4       0.0       0  ...     0.0       0        0        0      0      0   
5       1.0       0  ...     0.0       0        0        0      0      0   
6       0.0       1  ...     0.0       0        0        0      0      0   
7       0.0       0  ...     0.0       0        0        0      0      0   
8       0.0       0  ...     0.5       0        0        0      0      0   
9       2.0       0  ...     1.0       1        0        0      0      0   
10      2.0       0  ...     1.0       1        0        0      0      0   
11      1.0       2  ...     1.0       1        0        0      0      0   
12      0.0       1  ...     0.0       0        0        1      1      1   
13      1.0       0  ...     0.0       0        1        1      1      1   
14      0.0       0  ...     0.0       0        0        0      0      0   
15      0.0       0  ...     0.0       0        0        0      0      1   
16      0.0       0  ...     0.0       1        0        0      0      0   
17      0.0       0  ...     1.0       0        0        1      0      0   
18      0.0       0  ...     1.0       1        0        0      0      0   
19      

In [52]:
regularModel = maindf.to_numpy()
regularModel

array([[0., 2., 2., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 2., 2.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [31]:
eigs(regularModel)

(array([ 6.53353189+0.j        ,  3.60974234+0.j        ,
         3.15272712+0.75582448j,  3.15272712-0.75582448j,
        -0.86431795+2.16164087j, -0.86431795-2.16164087j]),
 array([[-0.33687336+0.j        , -0.03526508+0.j        ,
          0.03843221+0.21795589j,  0.03843221-0.21795589j,
          0.11487548-0.05026538j,  0.11487548+0.05026538j],
        [-0.1625976 +0.j        ,  0.06699334+0.j        ,
         -0.05302566+0.09395964j, -0.05302566-0.09395964j,
         -0.18116992-0.07958379j, -0.18116992+0.07958379j],
        [-0.06836903+0.j        , -0.03430758+0.j        ,
         -0.05550548+0.00256394j, -0.05550548-0.00256394j,
          0.15886848+0.02273817j,  0.15886848-0.02273817j],
        [-0.20417568+0.j        , -0.03912348+0.j        ,
          0.04276466+0.09382179j,  0.04276466-0.09382179j,
          0.23555387-0.01709989j,  0.23555387+0.01709989j],
        [-0.19122956+0.j        ,  0.26104745+0.j        ,
          0.08051275+0.06367973j,  0.08051275-0.06367

In [21]:
import numpy as np
from scipy.sparse.linalg import eigs

In [86]:
val,vec = eigs(regularModel, which='LM', k=1)
vec

array([[0.34101927+0.j],
       [0.16440717+0.j],
       [0.06768852+0.j],
       [0.20613305+0.j],
       [0.19626152+0.j],
       [0.13844715+0.j],
       [0.33415071+0.j],
       [0.10434471+0.j],
       [0.08586854+0.j],
       [0.19344547+0.j],
       [0.19876992+0.j],
       [0.23480073+0.j],
       [0.19713943+0.j],
       [0.18387649+0.j],
       [0.02846026+0.j],
       [0.04734075+0.j],
       [0.15187262+0.j],
       [0.26252521+0.j],
       [0.19254019+0.j],
       [0.23855315+0.j],
       [0.11075517+0.j],
       [0.13654788+0.j],
       [0.09407923+0.j],
       [0.07947878+0.j],
       [0.21849878+0.j],
       [0.10397008+0.j],
       [0.11089129+0.j],
       [0.08453219+0.j],
       [0.19748278+0.j],
       [0.22278769+0.j],
       [0.07770727+0.j],
       [0.09747604+0.j]])

In [87]:
vec = np.ndarray.flatten(abs(vec))

In [88]:
sorted_indices = vec.argsort()

In [89]:
sorted_indices

array([14, 15,  2, 30, 23, 27,  8, 22, 31, 25,  7, 20, 26, 21,  5, 16,  1,
       13, 18,  9,  4, 12, 28, 10,  3, 24, 29, 11, 19, 17,  6,  0])

In [36]:
teams = ["Bills",
"Patriots",
"Jets",
"Dolphins",
"Raiders",
"Chargers",
"Chiefs",
"Broncos",
"Bengals",
"Ravens",
"Browns",
"Steelers",
"Titans",
"Colts",
"Jaguars",
"Texans",
"49ers",
"Seahawks",
"Cardinals",
"Rams",
"Giants",
"Washington",
"Eagles",
"Cowboys",
"Packers",
"Vikings",
"Bears",
"Lions",
"Buccaneers",
"Saints",
"Falcons",
"Panthers",
]

In [90]:
ranked = [(teams[i], vec[i]) for i in sorted_indices]

In [91]:
ranked.reverse()

In [92]:
ranked ##SUCCESS: Regular

[('Bills', 0.3410192667327775),
 ('Chiefs', 0.3341507107638658),
 ('Seahawks', 0.262525207455415),
 ('Rams', 0.23855314705538067),
 ('Steelers', 0.2348007318601549),
 ('Saints', 0.22278769454566819),
 ('Packers', 0.21849877976449067),
 ('Dolphins', 0.20613305420840794),
 ('Browns', 0.19876992216835332),
 ('Buccaneers', 0.19748277993027852),
 ('Titans', 0.19713943360508437),
 ('Raiders', 0.19626151695070745),
 ('Ravens', 0.1934454672732016),
 ('Cardinals', 0.19254019191079466),
 ('Colts', 0.18387649388447241),
 ('Patriots', 0.1644071742815043),
 ('49ers', 0.15187261586478282),
 ('Chargers', 0.13844715464217008),
 ('Washington', 0.13654788172011137),
 ('Bears', 0.1108912857677105),
 ('Giants', 0.11075517127198842),
 ('Broncos', 0.10434471226897969),
 ('Vikings', 0.1039700774745563),
 ('Panthers', 0.09747603549339978),
 ('Eagles', 0.09407922607708326),
 ('Bengals', 0.08586853887509077),
 ('Lions', 0.0845321900195738),
 ('Cowboys', 0.07947877824227949),
 ('Falcons', 0.07770727026050779),
 

In [57]:
colleydf = pd.read_csv('/Users/ranbarasan/Documents/NFLWinLossNormalChart.csv')

In [59]:
del colleydf['Unnamed: 0']
del colleydf['Unnamed: 33']
colleydf = colleydf.drop(index = 32)

In [61]:
colleyModel = colleydf.to_numpy()

In [63]:
for j in range(32):
    for i in range(32):
        if(i == j):
            colleyModel[i][j] = 16
        if(colleyModel[i][j] == 2):
            colleyModel[i][j] = -2 
        if(colleyModel[i][j] == 1):
            colleyModel[i][j] = -1

In [64]:
colleyModel

array([[16., -2., -2., ...,  0.,  0.,  0.],
       [ 0., 16., -2., ...,  0.,  0.,  0.],
       [ 0.,  0., 16., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., 16., -2., -2.],
       [ 0.,  0.,  0., ...,  0., 16., -1.],
       [ 0.,  0.,  0., ...,  0., -1., 16.]])

In [66]:
#colley formula for B
b = [6,
0,
-5,
3,
1,
0,
7,
-2,
-2.5,
4,
4,
5,
4,
4,
-6,
-3,
-1,
5,
1,
3,
-1,
0,
-2.5,
-1,
6,
0,
1,
-2,
4,
5,
-2,
-3]

In [93]:
from scipy.linalg import solve
vec = solve(colleyModel,b)
vec

array([ 0.39307547, -0.00846532, -0.28633314,  0.13358035,  0.06809791,
       -0.03723706,  0.44005398, -0.15028284, -0.15813394,  0.21031678,
        0.21481479,  0.30011553,  0.20148222,  0.19218096, -0.36298869,
       -0.24306   , -0.05763922,  0.28473429,  0.06246324,  0.20385503,
       -0.06657945, -0.02162799, -0.14861563, -0.09760243,  0.30836844,
       -0.05104384, -0.00391637, -0.15451725,  0.19882687,  0.26490401,
       -0.14620619, -0.20607033])

In [95]:
sorted_indices = vec.argsort()

In [96]:
sorted_indices

array([14,  2, 15, 31,  8, 27,  7, 22, 30, 23, 20, 16, 25,  5, 21,  1, 26,
       18,  4,  3, 13, 28, 12, 19,  9, 10, 29, 17, 11, 24,  0,  6])

In [97]:
ranked = [(teams[i], vec[i]) for i in sorted_indices]

In [99]:
ranked.reverse()

In [101]:
##SUCCESS: Colley Model
ranked

[('Chiefs', 0.4400539795685035),
 ('Bills', 0.3930754653265166),
 ('Packers', 0.3083684432637344),
 ('Steelers', 0.30011553374449323),
 ('Seahawks', 0.28473428873944095),
 ('Saints', 0.2649040071639393),
 ('Browns', 0.21481478975744112),
 ('Ravens', 0.21031677881879718),
 ('Rams', 0.20385502877387834),
 ('Titans', 0.20148222078869174),
 ('Buccaneers', 0.19882686838711774),
 ('Colts', 0.19218095968793683),
 ('Dolphins', 0.13358035494459602),
 ('Raiders', 0.06809791061019359),
 ('Cardinals', 0.062463243251954355),
 ('Bears', -0.003916366022585904),
 ('Patriots', -0.008465315149106784),
 ('Washington', -0.021627988023132542),
 ('Chargers', -0.03723705732766464),
 ('Vikings', -0.05104383978071672),
 ('49ers', -0.05763922361617406),
 ('Giants', -0.06657945405407481),
 ('Cowboys', -0.0976024271675968),
 ('Falcons', -0.1462061937262849),
 ('Eagles', -0.14861563283191748),
 ('Broncos', -0.15028284260729427),
 ('Lions', -0.15451724965872204),
 ('Bengals', -0.15813394472645545),
 ('Panthers', -0